### ISSUE TITLE
Strange dialog messages in several specific inputs

### ISSUE THREAD

**Issue by TranHuuNhatHuy** [suzil/radis-app#537]
Hi, I noticed several times the radis web app returns implicit or strange messages.

1. "Failed to retrieve data from given parameters" observed in CF4 and ClONO2 and some other cases that I didn't capture, but I'm sure more than these 2 cases.
![dataretrieve_CF4_issue](https://user-images.githubusercontent.com/29034232/160139451-fabc614a-a6e1-4d16-ac46-fc34738630b6.png)
![dataretrive_ClONO2_issue](https://user-images.githubusercontent.com/29034232/160139465-98b34482-e63f-4ba7-8e2e-493a298a0319.png)

2. "ju", just a weird message, observed in C2H4
![ju_C2H4_issue](https://user-images.githubusercontent.com/29034232/160139613-2aa5ab4c-c0d4-4c22-93d0-d0802558de95.png)

I used default parameters as you can see in the screenshots. These messages prevailed when I tried to reload the page or re-enter the parameters.

**Comment by suzil** [comment]
Right now we send back what the RADIS backend gives us: https://github.com/suzil/radis-app/blob/main/lib/radis-lambda/app.py#L71

The `ju` message is a little funny though!

I'm able to reproduce it and I can see the stack trace from the logs:
```
Impossible to parse local quanta in /tmp/.radisdb/hitran/downloads__can_be_deleted/C2H4/C2H4_1.data, probably an unlabelled line. Ignoring, but nonequilibrium calculations will not be possible. See details above.
Traceback (most recent call last):
File "/var/task/app.py", line 35, in lambda_handler
spectrum = radis.calc_spectrum(
File "/var/task/radis/lbl/calc.py", line 508, in calc_spectrum
generated_spectrum = _calc_spectrum_one_molecule(
File "/var/task/radis/lbl/calc.py", line 721, in _calc_spectrum_one_molecule
sf.fetch_databank(**conditions)
File "/var/task/radis/lbl/loader.py", line 1153, in fetch_databank
df, local_paths = fetch_hitran(
File "/var/task/radis/io/hitran.py", line 1399, in fetch_hitran
ldb.download_and_parse(download_files, cache=cache, parse_quanta=parse_quanta)
File "/var/task/radis/io/hitran.py", line 1191, in download_and_parse
writer.combine_temp_batch_files(
File "/var/task/radis/io/hdf5.py", line 188, in combine_temp_batch_files
df.sort(by=sort_values).export_hdf5(file, group=key, mode="w")
File "/var/task/vaex/dataframe.py", line 6740, in export_hdf5
writer.layout(self, progress=progressbar_layout)
File "/var/task/vaex/hdf5/writer.py", line 66, in layout
has_null = {name:df.is_masked(name) for name, dtype in dtypes.items() if not dtype.is_string}
File "/var/task/vaex/hdf5/writer.py", line 66, in <dictcomp>
has_null = {name:df.is_masked(name) for name, dtype in dtypes.items() if not dtype.is_string}
File "/var/task/vaex/dataframe.py", line 2213, in is_masked
return self.dataset.is_masked(column)
File "/var/task/vaex/dataset.py", line 558, in is_masked
return self.original.is_masked(column)
File "/var/task/vaex/dataset.py", line 760, in is_masked
return any(k.is_masked(column) for k in self.datasets)
File "/var/task/vaex/dataset.py", line 760, in <genexpr>
return any(k.is_masked(column) for k in self.datasets)
File "/var/task/vaex/dataset.py", line 1445, in is_masked
ar = self._columns[column]
KeyError: 'ju'
[31mWarning : 2 files were written but not combined. Deleting them.
['/tmp/.radisdb/hitran/C2H4_temp000000.hdf5', '/tmp/.radisdb/hitran/C2H4_temp000001.hdf5'][0m
```

@erwanp would you know how to debug this?
